<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0;net48</TargetFrameworks>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.msbuild" Version="10.0.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Xml" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.12" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
		<PackageReference Include="Microsoft.Testing.Extensions.HtmlReport" Version="2.4.1" />
		<PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.4.1" />
		<PackageReference Include="Microsoft.Testing.Platform" Version="2.4.1" />
		<PackageReference Include="xunit.v3" Version="4.0.1" />
		<PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector" Version="10.0.1">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Fededim.Extensions.Configuration.Protected.DataProtectionAPI\Fededim.Extensions.Configuration.Protected.DataProtectionAPI.csproj" />
	</ItemGroup>

	<ItemGroup>
		<VSTestLogger Include="trx%3BLogFileName=TestResults-$(TargetFramework)-$(MSBuildProjectName).trx%3Bverbosity=normal" />
		<!--<VSTestLogger Include="html%3BLogFileName=TestResults-$(TargetFramework)-$(MSBuildProjectName).html%3Bverbosity=detailed" />-->
	</ItemGroup>

	<PropertyGroup>
		<TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
	</PropertyGroup>

	<PropertyGroup>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<VSTestLogger>@(VSTestLogger)</VSTestLogger>
	</PropertyGroup>

</Project>
